test ci

diff --git a/.github/workflows/test-build.yml b/.github/workflows/test-build.yml
--- a/.github/workflows/test-build.yml
+++ b/.github/workflows/test-build.yml
@@ -30,143 +30,143 @@ jobs:
         mkdir -p ~/.cache/testmon
         rm -rf node_modules  ## TODO remove this later
 
-  addons:
-    runs-on: ubuntu-22.04
-    needs: build-cache
-    permissions:
-      checks: write
-    services:
-      postgres:
-        image: postgres
-        env:
-          POSTGRES_PASSWORD: ${{ env.OSF_DB_PASSWORD }}
-        options: >-
-          --health-cmd pg_isready
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-        ports:
-          # Maps tcp port 5432 on service container to the host
-          - 5432:5432
-    steps:
-    - uses: actions/checkout@v2
-    - uses: ./.github/actions/start-build
-    - name: Run tests
-      run: poetry run python3 -m invoke test-ci-addons -n 1 --junit
-    - name: Upload report
-      if: (github.event_name != 'pull_request') && (success() || failure())    # run this step even if previous step failed
-      uses: ./.github/actions/gen-report
+  # addons:
+  #   runs-on: ubuntu-22.04
+  #   needs: build-cache
+  #   permissions:
+  #     checks: write
+  #   services:
+  #     postgres:
+  #       image: postgres
+  #       env:
+  #         POSTGRES_PASSWORD: ${{ env.OSF_DB_PASSWORD }}
+  #       options: >-
+  #         --health-cmd pg_isready
+  #         --health-interval 10s
+  #         --health-timeout 5s
+  #         --health-retries 5
+  #       ports:
+  #         # Maps tcp port 5432 on service container to the host
+  #         - 5432:5432
+  #   steps:
+  #   - uses: actions/checkout@v2
+  #   - uses: ./.github/actions/start-build
+  #   - name: Run tests
+  #     run: poetry run python3 -m invoke test-ci-addons -n 1 --junit
+  #   - name: Upload report
+  #     if: (github.event_name != 'pull_request') && (success() || failure())    # run this step even if previous step failed
+  #     uses: ./.github/actions/gen-report
 
-  website:
-    runs-on: ubuntu-22.04
-    needs: build-cache
-    permissions:
-      checks: write
-    services:
-      postgres:
-        image: postgres
-        env:
-          POSTGRES_PASSWORD: ${{ env.OSF_DB_PASSWORD }}
-        options: >-
-          --health-cmd pg_isready
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-        ports:
-          # Maps tcp port 5432 on service container to the host
-          - 5432:5432
-    steps:
-    - uses: actions/checkout@v2
-    - uses: ./.github/actions/start-build
-    - name: Run tests
-      run: poetry run python3 -m invoke test-ci-website -n 1 --junit
-    - name: Upload report
-      if: (github.event_name != 'pull_request') && (success() || failure())    # run this step even if previous step failed
-      uses: ./.github/actions/gen-report
+  # website:
+  #   runs-on: ubuntu-22.04
+  #   needs: build-cache
+  #   permissions:
+  #     checks: write
+  #   services:
+  #     postgres:
+  #       image: postgres
+  #       env:
+  #         POSTGRES_PASSWORD: ${{ env.OSF_DB_PASSWORD }}
+  #       options: >-
+  #         --health-cmd pg_isready
+  #         --health-interval 10s
+  #         --health-timeout 5s
+  #         --health-retries 5
+  #       ports:
+  #         # Maps tcp port 5432 on service container to the host
+  #         - 5432:5432
+  #   steps:
+  #   - uses: actions/checkout@v2
+  #   - uses: ./.github/actions/start-build
+  #   - name: Run tests
+  #     run: poetry run python3 -m invoke test-ci-website -n 1 --junit
+  #   - name: Upload report
+  #     if: (github.event_name != 'pull_request') && (success() || failure())    # run this step even if previous step failed
+  #     uses: ./.github/actions/gen-report
 
-  api1_and_js:
-    runs-on: ubuntu-22.04
-    needs: build-cache
-    permissions:
-      checks: write
-    services:
-      postgres:
-        image: postgres
-        env:
-          POSTGRES_PASSWORD: ${{ env.OSF_DB_PASSWORD }}
-        options: >-
-          --health-cmd pg_isready
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-        ports:
-          # Maps tcp port 5432 on service container to the host
-          - 5432:5432
-    steps:
-      - uses: actions/checkout@v2
-      - uses: ./.github/actions/start-build
-      - name: NVM & yarn install
-        run: poetry run python3 -m invoke assets --dev
-      - name: Run test
-        run: poetry run python3 -m invoke test-ci-api1-and-js -n 1 --junit
-      - name: Upload report
-        if: (github.event_name != 'pull_request') && (success() || failure())    # run this step even if previous step failed
-        uses: ./.github/actions/gen-report
+  # api1_and_js:
+  #   runs-on: ubuntu-22.04
+  #   needs: build-cache
+  #   permissions:
+  #     checks: write
+  #   services:
+  #     postgres:
+  #       image: postgres
+  #       env:
+  #         POSTGRES_PASSWORD: ${{ env.OSF_DB_PASSWORD }}
+  #       options: >-
+  #         --health-cmd pg_isready
+  #         --health-interval 10s
+  #         --health-timeout 5s
+  #         --health-retries 5
+  #       ports:
+  #         # Maps tcp port 5432 on service container to the host
+  #         - 5432:5432
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - uses: ./.github/actions/start-build
+  #     - name: NVM & yarn install
+  #       run: poetry run python3 -m invoke assets --dev
+  #     - name: Run test
+  #       run: poetry run python3 -m invoke test-ci-api1-and-js -n 1 --junit
+  #     - name: Upload report
+  #       if: (github.event_name != 'pull_request') && (success() || failure())    # run this step even if previous step failed
+  #       uses: ./.github/actions/gen-report
 
-  api2:
-    runs-on: ubuntu-22.04
-    needs: build-cache
-    permissions:
-      checks: write
-    services:
-      postgres:
-        image: postgres
-        env:
-          POSTGRES_PASSWORD: ${{ env.OSF_DB_PASSWORD }}
-        options: >-
-          --health-cmd pg_isready
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-        ports:
-          # Maps tcp port 5432 on service container to the host
-          - 5432:5432
-    steps:
-    - uses: actions/checkout@v2
-    - uses: ./.github/actions/start-build
-    - name: Run tests
-      run: poetry run python3 -m invoke test-ci-api2 -n 1 --junit
-    - name: Upload report
-      if: (github.event_name != 'pull_request') && (success() || failure())    # run this step even if previous step failed
-      uses: ./.github/actions/gen-report
+  # api2:
+  #   runs-on: ubuntu-22.04
+  #   needs: build-cache
+  #   permissions:
+  #     checks: write
+  #   services:
+  #     postgres:
+  #       image: postgres
+  #       env:
+  #         POSTGRES_PASSWORD: ${{ env.OSF_DB_PASSWORD }}
+  #       options: >-
+  #         --health-cmd pg_isready
+  #         --health-interval 10s
+  #         --health-timeout 5s
+  #         --health-retries 5
+  #       ports:
+  #         # Maps tcp port 5432 on service container to the host
+  #         - 5432:5432
+  #   steps:
+  #   - uses: actions/checkout@v2
+  #   - uses: ./.github/actions/start-build
+  #   - name: Run tests
+  #     run: poetry run python3 -m invoke test-ci-api2 -n 1 --junit
+  #   - name: Upload report
+  #     if: (github.event_name != 'pull_request') && (success() || failure())    # run this step even if previous step failed
+  #     uses: ./.github/actions/gen-report
 
-  api3_and_osf:
-    runs-on: ubuntu-22.04
-    permissions:
-      checks: write
-    needs: build-cache
-    services:
-      postgres:
-        image: postgres
+  # api3_and_osf:
+  #   runs-on: ubuntu-22.04
+  #   permissions:
+  #     checks: write
+  #   needs: build-cache
+  #   services:
+  #     postgres:
+  #       image: postgres
 
-        env:
-          POSTGRES_PASSWORD: ${{ env.OSF_DB_PASSWORD }}
-        options: >-
-          --health-cmd pg_isready
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-        ports:
-          # Maps tcp port 5432 on service container to the host
-          - 5432:5432
-    steps:
-    - uses: actions/checkout@v2
-    - uses: ./.github/actions/start-build
-    - name: Run tests
-      run: poetry run python3 -m invoke test-ci-api3-and-osf -n 1 --junit
-    - name: Upload report
-      if: (github.event_name != 'pull_request') && (success() || failure())    # run this step even if previous step failed
-      uses: ./.github/actions/gen-report
+  #       env:
+  #         POSTGRES_PASSWORD: ${{ env.OSF_DB_PASSWORD }}
+  #       options: >-
+  #         --health-cmd pg_isready
+  #         --health-interval 10s
+  #         --health-timeout 5s
+  #         --health-retries 5
+  #       ports:
+  #         # Maps tcp port 5432 on service container to the host
+  #         - 5432:5432
+  #   steps:
+  #   - uses: actions/checkout@v2
+  #   - uses: ./.github/actions/start-build
+  #   - name: Run tests
+  #     run: poetry run python3 -m invoke test-ci-api3-and-osf -n 1 --junit
+  #   - name: Upload report
+  #     if: (github.event_name != 'pull_request') && (success() || failure())    # run this step even if previous step failed
+  #     uses: ./.github/actions/gen-report
 
   mailhog:
     runs-on: ubuntu-22.04
